export const authConstants = {
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_FAILURE: "LOGIN_FAILURE",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGOUT_REQUEST: "LOGOUT_REQUEST"

}

export const adminContants = {
    ADMIN_REGISTER_REQUEST: "ADMIN_REGISTER_REQUEST",
    ADMIN_REGISTER_SUCCESS: "ADMIN_REGISTER_SUCCESS",
    ADMIN_REGISTER_FAILURE: "ADMIN_REGISTER_FAILURE",
  };